export const REPORT_ALUMNO_ATTRIBUTES = [
    'id',
    'id_tipodocumento',
    'id_pais',
    'id_departamento',
    'numero_documento',
    'apellido_paterno',
    'apellido_materno',
    'nombres',
    'telefono',
    'direccion',
    'email',
    'fecha_nacimiento',
    'nombre_capitalized',
    'fecha_nacimiento_str',
    'sexo',
    'sistema',
    'estado'
]